### ISSUE TITLE
creating/deleting snapshots are not returning status

### ISSUE THREAD

**Issue by kishore0709** [BigDataBoutique/elasticsearch-repository-swift#2]
Hi,

I'm writing a backup script(in python) on our Elasticsearch clusters, in that script 

- I'm trying to initiate snapshot process and come out(If i get 200 response code later again i'll run snapshot status to know whether snapshot is success or in_progress etc..) but here my snapshot command is not returning response code even though i  provided wait_for_completion=false. Please suggest. 

- Same thing is happening with delete.

**Comment by kishore0709** [comment]
I'm using swift_repo plugin 2.4.1

**Comment by synhershko** [comment]
Hi, we are in the process of refactoring the codebase, we will review this issue when we are done to make sure it was addressed. Thanks!

**Comment by synhershko** [comment]
Hi, we just pushed some fixes that should address this (ES 6.x). Because it's been a while since you posted this, I'm going to close it now but please feel free to reopen with more details if this is still an issue. Thanks.
