### ISSUE TITLE
keystone v3 support？

### ISSUE THREAD

**Issue by osmboy** [BigDataBoutique/elasticsearch-repository-swift#7]

**Comment by R4il** [comment]
I was looking into both keystone v3 and the required changes to update this plugin to support ES 7.x. Not sure if there is much planed in either regard as this repo seems to be on a low activity/just basic support.

**Comment by synhershko** [comment]
Fixed by https://github.com/BigDataBoutique/elasticsearch-repository-swift/pull/11
