### ISSUE TITLE
Q: Is ElasticSearch 7 supported?

### ISSUE THREAD

**Issue by agis** [BigDataBoutique/elasticsearch-repository-swift#8]
This is not an issue, just a question. Just wanted to know if ElasticSearch 7 (and specifically 7.7) is supported.

**Comment by agis** [comment]
@synhershko Hey, thanks for this plugin. Pinging you to ask if ES 7.x is supported. Thanks in advance!

**Comment by alikhanich** [comment]
I could not even build it. Guessing es7 is not supported

**Comment by synhershko** [comment]
Fixed by https://github.com/BigDataBoutique/elasticsearch-repository-swift/pull/11
